const products = [
  {
    id: 1,
    name: "Apple",
    price: 3.6,
    offerPercent: 30,
    weight: "1 Kg",
    category: "fruits",
    image: "/media/products/apple.jpg",
    inventory: 20,
  },
  {
    id: 2,
    name: "Mango",
    price: 5,
    offerPercent: 50,
    weight: "1 Kg",
    category: "fruits",
    image: "/media/products/mango.jpg",
    inventory: 20,
  },
  {
    id: 3,
    name: "Orange",
    weight: "1 Kg",
    offerPercent: 50,
    price: 3.5,
    category: "fruits",
    image: "/media/products/orange.jpg",
    inventory: 20,
  },
  {
    id: 4,
    name: "Grapes",
    price: 6.5,
    offerPercent: 80,
    weight: "1 Kg",
    category: "fruits",
    image: "/media/products/grapes.jpg",
    inventory: 20,
  },
  {
    id: 5,
    name: "Water Melon",
    price: 4.7,
    weight: "1 Kg",
    category: "fruits",
    image: "/media/products/water-melon.jpg",
    inventory: 20,
  },
  {
    id: 6,
    name: "Banana",
    price: 3.15,
    weight: "1 Kg",
    category: "fruits",
    image: "/media/products/banana.jpg",
    inventory: 20,
  },
  {
    id: 7,
    name: "Carrot",
    price: 2.50,
    offerPercent: 50,
    weight: "1 Kg",
    category: "vegetables",
    image: "/media/products/carrots.jpg",
    inventory: 20,
  },
  {
    id: 8,
    name: "Potato",
    price: 1.50,
    offerPercent: 30,
    weight: "1 Kg",
    category: "vegetables",
    image: "/media/products/potato.jpg",
    inventory: 20,
  },
  {
    id: 9,
    name: "Onion",
    price: 1.50,
    offerPercent: 50,
    weight: "1 Kg",
    category: "vegetables",
    image: "/media/products/onion.jpg",
    inventory: 20,
  },
  {
    id: 10,
    name: "Corn",
    price: 1.80,
    offerPercent: 80,
    weight: "1 Kg",
    category: "vegetables",
    image: "/media/products/corn.jpg",
  },
  {
    id: 11,
    name: "Detergent Liquid",
    price: 8.65,
    offerPercent: 30,
    weight: "2 Ltr",
    category: "household",
    image: "/media/products/detergent-liquid.jpg",
    inventory: 20,
  },
  {
    id: 12,
    name: "Bathroom Cleaner",
    price: 7.75,
    weight: "5 Ltr",
    offerPercent: 50,
    category: "household",
    image: "/media/products/bathroom-cleaner.jpg",
    inventory: 20,
  },
  {
    id: 13,
    name: "Mop with Bucket",
    price: 20.00,
    weight: "1 Set",
    offerPercent: 50,
    category: "household",
    image: "/media/products/mop.jpg",
    inventory: 20,
  },
  {
    id: 14,
    name: "Toilet Brush with Holder",
    price: 6.50,
    weight: "1 Set",
    offerPercent: 80,
    category: "household",
    image: "/media/products/toilet-brush.jpg",
    inventory: 20,
  },
  {
    id: 15,
    name: "Hand Sanitizer",
    price: 3.50,
    weight: "500 Ml",
    category: "household",
    offerPercent: 80,
    image: "/media/products/hand-sanitizer.jpg",
    inventory: 20,
  },
];

export default products;
